server:
  port: 8888
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:UT;DB_CLOSE_DELAY=-1
    username: ut
    password: ut
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create